#!/bin/bash

#Sam Glendenning
#Matric: 160004927
#Will Lockett
#Matric: 160006641

clear

scriptDir="$(pwd)"
cd ..
mkdir Local\ Repositories
cd Local\ Repositories
homeDir="$(pwd)"
cd "$scriptDir"

printf "Welcome to the easy-to-use repository API.\n\n"

while [ "$input" != 5 ]
do
{
	sh displayRepos.sh

	printf "\nPlease select an option:\n"
	printf "1. Create a repository\n"
	printf "2. Open a local repository\n"
	printf "3. Checkout an online repository\n"
	printf "4. Delete an online repository\n"
	printf "5. Quit\n"

	read input

	while [ "$input" != 1 ] && [ "$input" != 2 ] && [ "$input" != 3 ] && [ "$input" != 4 ] && [ "$input" != 5 ] 
	do
	{
		if [ -z "$input" ]
		then
		{
			printf "You need to enter a value\n"	
		}
		else
		{
			printf "Error. Please enter a number 1 to 5.\n"
		}
		fi

		read input
	}
	done

	clear

	if [ "$input" == 1 ] 
	then
	{	
		sh makeRepo.sh 
	}
	elif [ "$input" == 2 ]
	then
	{
		sh displayRepos.sh
        return=$?

        if [ "$return" = 0 ]
        then
        {  
			sh openRepo.sh "$homeDir" "$scriptDir"
		}
		fi
	}
	elif [ "$input" == 3 ]
	then
	{
		sh displayRepos.sh
        return=$?

        if [ "$return" = 0 ]
        then
        {  
			sh checkoutRepo.sh "$homeDir"
		}
		fi
	}
	elif [ "$input" == 4 ]
	then
	{
		sh displayRepos.sh
        return=$?

        if [ "$return" = 0 ]
        then
        {  
			sh deleteRepo.sh
		}
		fi
	}
	fi
	
	clear
	cd "$scriptDir"
}
done

cd "$scriptDir"

exit 0
